### ISSUE TITLE
Plugin usage with known playlists

### ISSUE THREAD

**Issue by aedicted** [chandler-stimson/live-stream-downloader#1]
Hello, 

since the actually for-this-more-suitable-tool "Streamlink" is quite buggy when it comes to random read timeout errors for whatever reason, I'm looking for an alternative which is capable to download segments from m3u8 playlists in multiple threads to increase the effective data throughput and resemble them in one file.

While your tool seems to support URL detection from websites, I wonder how I can use your tool when I  already know the m3u8-URL of a specific stream. At least in text form or entered a HREF in an HTML file, it doesn't seem to detect anything ...

**Comment by chandler-stimson** [comment]
As of v0.1.1 release, you can use the right-click context menu over the browser action and parse a local M3U8 file. It is treated as the manifest is received from this page. So you will get the badge icon if there are segments.
