### ISSUE TITLE
Crash during downloading at ~80% or even at 100% percent

### ISSUE THREAD

**Issue by ljx3000** [chandler-stimson/live-stream-downloader#10]
It's a very great add-on to download videos.
But sometimes, it is crash during downloading at ~80% or even at 100% percent. Some links will be OK after several tries, but some links never success and always crash at 100%.
E.g. 
https://1252524126.vod2.myqcloud.com/9764a7a5vodtransgzp1252524126/1664e7945285890811836944617/drm/v.f100230.m3u8?time=1609033248311

**Comment by ljx3000** [comment]
I have installed the latest version from Goole Chrome Addons store already

**Comment by chandler-stimson** [comment]
Can you try with 0.2.4 release?
