### ISSUE TITLE
Update firefox version

### ISSUE THREAD

**Issue by trimechee** [chandler-stimson/live-stream-downloader#100]
Hi, it is good to have firefox alternative version to chrome store version because chrome store can limit or censor extensions , and i discover yesterday the last firefox version is 0.5.0 and last version date goes back to 2 months ago (15 sept. 2024) while chrome version has been updated several times....

https://addons.mozilla.org/fr/firefox/addon/live-stream-downloader/versions/

we hope for a next update please, thanks !

**Comment by chandler-stimson** [comment]
I've already submitted the latest release. Still under review.
