### ISSUE TITLE
Issue with Video Downloads: Only First Few Seconds Downloaded

### ISSUE THREAD

**Issue by hyhakisaku** [chandler-stimson/live-stream-downloader#101]
This extension previously allowed downloading full videos from this website, but recently, it only downloads the first few seconds. Could you kindly advise if there's a way to resolve this issue? Additionally, the episode must be selected at the right side of the website before the video starts playing.(https://sn-video.com/page.php?2295)

**Comment by chandler-stimson** [comment]
thanks for the report. Please try the latest commit to confirm the fix.
