### ISSUE TITLE
Add support of Netu tv : a stable perennial capital platform which has a good network buffer and an anti-robot defense mechanism

### ISSUE THREAD

**Issue by trimechee** [chandler-stimson/live-stream-downloader#109]
Hi, I change streaming site and I discover other sites offering videos coming from the famous platform netu tv, it says netu tv has an anti-robot defense mechanism by constantly changing the position of the play button so famous netutv is a stable, sustainable perennial streaming platform ! 

unfortunately our beloved Live-Stream-Downloader cannot detect the netu tv videos that I found on this site,  for example:

netutv :

https://waaw.to/watch_video.php?v=cXovSG1FdGtPcFd3VnJnN0x2azNQT1pZQUt5T0NHeXpXTzNRYzBwVHc3NVBTQkt3MEVjUDdubnkwS0FuSG1OTA%3D%3D#iss=NDEuMjI3LjkwLjIzMA==

https://www.tirexo.tools/?p=manga&id=3841-sword-art-online-alternative-gun-gale-online-saison2

https://netu.ac/#current_file_chunk_upload_div_3

so I tested with Cat-Catch which also can't detect netu tv video, I searched on reddit and it says cococut and 9xbuddy can download netu tv video:

https://www.reddit.com/r/DataHoarder/comments/zs3dam/how_to_download_a_video_thats_hosted_on_netutv_i/?tl=fr&rdt=61710

https://cococut.net/

https://9xbuddy.com/fr
https://9xbuddy.online/fr
https://123sudo.com/desktop/9xbuddy
https://123sudo.com/mobile/9xbuddy
https://123sudo.com/fr

i haven't tested these tools, i'm not saying they are bad but i prefer to avoid using non open source extensions, on the other hand i have already spoken with the developer of Stream Recorder extension and Stream recorder from edge store can download netu tv video! :

https://www.altextension.com/stream/fr/index.html

we can download the edge version of stream recorder and put it in a chromium browser via this site :

https://robwu.nl/crxviewer/
https://github.com/Rob--W/crxviewer

and so I talked about all these tools and my tests to show that apparently, it seems that it is technically possible that a free extension can download from the famous netu tv platform and we hope our beloved Live-Stream-Downloader will be able to download from netu tv, thank you !

**Comment by chandler-stimson** [comment]
The interface now supports extracting media streams from VideoJS object. So although the extension still cannot detect links on this site, if you open the interface, you will see the extracted M3U8 stream.

**Comment by trimechee** [comment]
UPDATE : 

Just for test purpose, the link of netu tv that i posted change his url addresse because it adds protection : 

https://dl-protect.link/0ebeca2a?fn=U3dvcmQgQXJ0IE9ubGluZSBBbHRlcm5hdGl2ZSDCq0d1biBHYWxlIE9ubGluZcK7IC0gU2Fpc29uIDIgRXBpc29kZSAxIC0gW1ZPU1RGUl0%3D&rl=b1


here the new link of netu tv video : 

https://waaw.to/f/XEIF99mjrJQg


we can find netu videos in these sites : 

https://www.extreme-down.tools/?p=manga&id=3834-seirei-gensouki-spirit-chronicles-saison2


https://www.wawacity.center/
https://t.me/Wawacity_officiel



https://www.zone-telechargement.center/
https://t.me/ZT_officiel

https://www.annuaire-telechargement.center/
https://t.me/Annuaire_telechargement_officiel



https://www.tirexo.center/?p=mangas&s=vf
https://www.tirexo.center/?p=mangas&s=vostfr
https://www.tirexo.center/
https://t.me/tirexo_officielle
