### ISSUE TITLE
Does disabling browser cache help the extension avoid possible issues and better detect streams and download them?

### ISSUE THREAD

**Issue by trimechee** [chandler-stimson/live-stream-downloader#110]
Hi, since I can't see and playback temporary hls video in download folder and playback video while it's downloading, I check if there is a new version of FDM because it allows suequential download and let playback a video while it's downloading, but there is no new version because the actual version of FDM can't detect many videos from many websites.....  and I see users complaining they have to agree to anonymous data collection of FDM extension and FDM member answers to these users: "The FDM extension requires permissions to be able to intercept audio and video downloads (some of downloads are cached by the browser and thus it's required to have access to the browser history). If you're referring to other types of data collection, kindly contact the support team using the form found on the official FDM website."

so my question please, if we disable the cache, does it help Live-stream-downloader to avoid possible problems and better detect streams and download them?

if that is the case, I know several good forks of firefox and chromium and I am even ready, like probably other users, to install a new web browser and disable the cache just to be able to use the extension in optimal conditions!

**Comment by chandler-stimson** [comment]
No, browser caching has nothing to do with the stream detection.

Are you sure Chrome is not creating a hidden tmp file in your OS? There is no way it does not create a tmp file before downloading is over.

**Comment by trimechee** [comment]
Thank's for your help ! 

In Torium and Supermium 124 chromium kernel, I could see the temporary video file made by Live-Stream-Downloader and playback the video while it was downloading, since Supermium upgraded to chromium 126 lts, ​​I can't see the temporary video anymore....I tried to search in the hidden files of the browser, the os, the windows temporary folder... I can't find the video temporary file that I think resides in an encrypted file of the browser, maybe in  RAM.....

My trick was, in the cat catch settings, I enable "stream download" and disable "ffmpeg transcod" in the M3U8 parser and I could see the temporary video and the playback using catsxp browser which use the newest chromium kernel , but since catsxp browser migrates recently  to chromium 131 kernel, I can't see the temporary video anymore unfortunately.....        
 I contacted the developer of supermium, r3dfox browsers to ask them to add feature of dipslay temporary video file and the developer of r3dfox browser expressed his interest for this function and maybe r3dfox will be able to add this hoped long-awaited function....

i tried to put the link of the hls video detected by Live-stream-downloader in FDM, but it didn't work, for what reason please ? it would have been the dream that LIVE Sream Downloader was compatible with an external download manager like fdm, it would have allowed us to playback the video while it was downloaded!

**Comment by trimechee** [comment]
Mr Chandler, just to check if it comes from my old windows 7 os or does it affect other modern os, can you see the temporary video file, for example by downloading this hls video please ?

https://v6.voiranime.com/anime/shangri-la-frontier-2-vf/shangri-la-frontier-2-02-vf/

I have already activated for a long time the option  show hidden files in the windows 7 os settings, now  I enable the option : " show hidden protected  files of the os", I will try to do other tests and I will inform you of the result, thank you!

**Comment by chandler-stimson** [comment]
Yes, it does create `*.crswap` files for me. Check the size of the file generated with this extension—it's possible that Chrome is writing directly to the file instead of using `*.crswap`.

**Comment by trimechee** [comment]
Really !!! i din't know this capital news ! *.crswap in the donwload folder chosen in the browser settings ?

sadly there is no chrome version for my windows 7 os 32 bits , but i found a special chrome updated for windows 7 os , i will install it right away :


https://github.com/Blaukovitch/GOOGLE_CHROME_Windows_7

because maybe this bug comes from catsxp , or from my windows 7 os ....i will install the special chrome for windows 7 os and do some tests, thanks !

**Comment by chandler-stimson** [comment]
Chrome always creates this file next to the file that is downloading.

**Comment by trimechee** [comment]
Interesting! Thanks! i clear date , cache...of catsxp, same result, no temporary file, i will try chrome for windows 7.....the developer of r3dfox said to me he find my idea interesting to display temporary video file and I I gave the video link and the Live Stream donwloader extension to test so it suggests Firefox does not display video temporay file....there is also Firefox updated for windows 7 from the same developer Mr Blaukovitch, i will try it...thanks :)

**Comment by trimechee** [comment]
UPDATE :

GREAT NEWS ! Your advice and especially the crucial information you gave me that you can see the temporary video using chrome browser pushed me to install GOOGLE_CHROME_Windows_7 and it works !!!i can see and playback temporary file !  I am very happy and relieved alhamdoullAllah, thank you very much Mr @chandler-stimson and really in all objectivity, since I tested many when I had my windows 10 laptop before its crash, Live-stream-downloader is the best downloader in the world and unique in the sense very responsive to quickly fix problems, huge thanks  and gratitude for this vital jewel of technology ! 💯 🥇

**Comment by trimechee** [comment]
Mr @chandler-stimson , great news, alhamdoulilAllah i find the solution to display temporary files in chromium browsers and fix this major problem !! may be add this solution to FAQ? thanks :) 

https://github.com/win32ss/supermium/issues/1064

**Comment by trimechee** [comment]
To summarize, the solution to the probelm of temporary video not displayed and also for problems of preview feature with potplayer and Open in vlc (Mr Andy kindly add initial support of Potplayer and Qmplay2 in new commit  after my request)  and Cat catch  is just enable this option :  "continue running applications in the background after closing chrome" in

chrome://settings/system !!

**Comment by trimechee** [comment]
Update : it 's disaster, catastrophe , i don't understand what happens, even when i use Live stream donwloader, i don't see anymore temporary video !! because of the new updated version of catsxp and  yandex browsers ?!! only chrome 130 let me display temporary video both of  Live stream downloader and cat catch and, and i fear the new versio of chrome will delete the possiblity to see temporay video :(
