### ISSUE TITLE
Add option to zap skip the error message "an operation that depends on state cached in an interface object was made but the state has changed since it was read from disk" in order to be able to close the web browser when we activate option : "auto-close when done" 

### ISSUE THREAD

**Issue by trimechee** [chandler-stimson/live-stream-downloader#112]
Hi, I am now using updated google chrome for windows 7 to avoid problems with displaying temporary video, because I discovered that even by activating the option ": "continue running applications in the background after closing chrome" in

chrome://settings/system ,

yes it's great I can see temporary video of Live stream downloader when using supermium and catsxp browsers, but I can't see temporary file of cat catch extension when I use supermium and catsxp browsers, so updated chrome for windows 7 become my default web browser to avoid problems with dipslyaing temporary video, and chrome can consume a lot of resources especially since I have disabled in chrome://settings/performance, I have disabled the memory saver to avoid possible download problems because a video download extension recommends disabling the memory saver .....

so I use chrome which can be resource-intensive, and I activate in our beloved "Live stream downloader" the "auto close when done" option, because the download can take a long time and I can do other things and forget about chrome open and the error message sometimes displayed by "Live stream downloader: "an operation that depends on state cached in an interface object
was made but the state has changed since it was read from disk" prevents the web browser from closing automatically, so my request please is that the extension closes the web browser even if there is this error message because sometimes, I can forget my chrome open for a long time and I would like to save resources, thank you!

the error message "an operation that depends on state cached in an interface object
was made but the state has changed since it was read from disk" is surprising and enigmatic, sometimes this red error message appears when I playback the temporary video while downloading, sometimes it does not appear and I can playback the video while it is downloading and get a homogeneous video file at the end, sometimes this error message appears and the downloaded part of the video suddenly disappears, sometimes this error message appears and the temporary video does not disappear and remains in the download folder even when I close the extension and the web browser.....

i don't know what causes this mysterious behavior, I am doing some tests, enable/disable keep awake, enable/disable memory saver, change the number of threads....maybe this message appears when Live stream downloader fails to download a small hls video fragment? this kind of error happens to me sometimes in cat catch which has a button "relaunch the download of failed video fragments".....

in any case, on 5 attempts, I can playback temporary video without this error message, and once this error message appears and the downloaded temporary video is suddenly deleted, , and we hope please this error message will no longer prevent the web browser from closing please when we activate the option "auto close when done", maybe add an additional option "auto close web browser even if there is error message" or "add option "restart the download when there is an error", thank you!

**Comment by trimechee** [comment]
Update : today i finally export then import my bookmarks to update chrome for windows 7 which became my defaut browser, the errr message ""an operation that depends on state cached in an interface object was made but the state has changed since it was read from disk" occurs in supermium browser, so now i will test Live stream downloader with my favourite anime episode and see if this error still appears again :)

**Comment by trimechee** [comment]
Update : the error message appears even  in updated chrome for windows 7, this is strange, somtimes the error message appears and abort the dowwnload and delete the video whicj size become 0 octet, and somtime this error message doesn't appear when i playback video while donwading : ""an operation that depends on state cached in an interface object was made but the state has changed since it was read from disk"

**Comment by trimechee** [comment]
Update : Hi, since yesterday , i watch so i test many videos aime episodes with the new version of Cat-catch, i enable "stream download" option and disable "ffmpeg transcord" in m3u8 parser settings, also i enable "stream donwload" in downloader section , and i can playback temporary videos withtout problem and without error message like : "an operation that depends on state cached in an interface object was made but the state....."

so i talk about this because i thought that playback temporary videos caused this error message when using our beloved Live stream donwloader : "an operation that depends on state cached in an interface object was made but the state....." , 

but with cat catch extension, there is no this kind of error message when i playback temporary videos.....the most important in this bug is that Live stream donwloader deletes the temporary video when this error message appears, i.e. the size of the video becomes 0 bytes, we hope please this problem will be solved please Mr @chandler-stimson :)

**Comment by chandler-stimson** [comment]
This issue might occur when reading and writing simultaneously. Instead of playing the temporary file directly, try copying it to a new file, such as `a.mkv`, and then play that file. If you later copy additional segments to the same file name, the player will retain the previous seek position and resume playback seamlessly.

**Comment by trimechee** [comment]
Thank you very much for your precious help!

by the way, i realize now that i tested the new version of Live stream downloader after fresh reinstallation of potplayer where i lost my potplayer settings and i forgot to enable the 2 resume video options of potplayer, because i start to believe it is potplayer that was causing this error, because i payback the video from the beginning when i watch 5 minutes, or 10 minutes of temporary video then i replayback again temporary video from the beginning after a time interval ....

because after this error, i went to use cat catch where also i could not resume temporary video, so i found out i forgot to enable resume video in playlist of potplayer, and so i used cat catch with resume video feature enabled of potplayer and i do not replayback temporary video from the beginning ....

i will do some tests with resume video of potplayer enabled and with Live stream downloader, if the error comes back again, so I will follow your advice, thank you very much Mr Chandler for your help :)

also lest notice I disabled the "enable write cache...." option on my hdd hard drive, because I don't have a battery and disabling this option apparently prevents data loss... I'm also going to reactivate this hard drive option and do some tests again...

**Comment by trimechee** [comment]
Ahh, I remember an interesting thing that could explain this error message, Live stream downloader downloads the video with .mkv format, but cat catch where this error message does not occur downloads the video with .ts format...I will do more comparative tests, I will even restore the default value of file name, put the number of threads back to 2....

**Comment by trimechee** [comment]
UPDATE : Mr @chandler-stimson , great news ! 

i reset some settings of Live stream downloader , the file name, number of threads=2 (previously number of threads was= 1) , and i enable the 2 options of resume videos of Potplayer, and i try with 3 videos , this error message does not appear and i can playback the video while downloading without needing to do other manipulations.....

thanks, for now, i close this issue, great Live-stream-downloader becomes my default downloader again, so i will have the opportunity to test it intensively and see if this bug comes back or not, if it does not come back, then the problem was caused either by the number of threads or by potplayer which replays temporary video from the beginning, and enabling the 2 options of resume video apparently allows to fix this problem, but i will do more tests to verify...

**Comment by trimechee** [comment]
Update : this error message is still back when deleting the temporary video, I noticed it apparently happens when I forget to replayback the temporary video frequently,

replayback temporary video is useful because it allows to playback a larger part of the temporary video and with resume feature of potplayer, we replay the video where we stopped, I continue to replayback the temporary video frequently to check if it avoids this error message, note I downloaded temporary videos with cat catch and from what I remember, this error message gene has never been displayed, but Live stream downloader is more powerful than Cat Catch to detect jwplayer / videojs object, in addition the auto close browser feature works unlike Cat catch where this close browser when finish option does not work, Cat catch is very powerful but our beoved Live stream downloader remains the Number 1 and the best downloader in the world, bravoo and thank you immense gratitude to Mr Chandler @chandler-stimson  !
