### ISSUE TITLE
New update made it no longer work.

### ISSUE THREAD

**Issue by ebiggs53135** [chandler-stimson/live-stream-downloader#13]
This was working beautifully for me, but once the newest update was pushed, I no longer have the "Remove non-HLS streams" button, and all the short audio segments to the stream are showing up individually, rather than as one option to be downloaded and automatically stitched together.

**Comment by chandler-stimson** [comment]
As of the new release, all "M3U8" manifests are sorted on top of the list. There is no need for that button anymore. You just need to select it to grab all segments and combine them.
