### ISSUE TITLE
search url with txt file

### ISSUE THREAD

**Issue by Lucifer502** [chandler-stimson/live-stream-downloader#16]
It would be great if it also searched for url .txt

**Comment by Lucifer502** [comment]
search how are you url 

https://v.vrv.co/evs/16546636a63782642606b37937397e11/assets/32412d344795f33f25c8c8150d8eae1c_270433.txt?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly92LnZydi5jby9ldnMvMTY1NDY2MzZhNjM3ODI2NDI2MDZiMzc5MzczOTdlMTEvYXNzZXRzLzMyNDEyZDM0NDc5NWYzM2YyNWM4YzgxNTBkOGVhZTFjXzI3MDQzMy50eHQiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NDUwNzAyNzd9fX1dfQ__&Signature=ZOZRiNDr9n46Ih0-Og-x54onoiiKwuaVTUL9QID3jct~TAEbRT5-YGT6R491yP4LKrcQzVTW5fS18dEkLaq8fMWhotXAmjZ~wYB~KszJZMesCWYjlx5hxb~WxC-90PvHyqZvCoyYKsDsxBPvFniwsUqenW6BWIbHeQx1hkdJZzvGEmR0GG6E-bhDOYye25Qo8QemT~6R~Ru~mAP~Kc7xIkGu3hfhQjxXlVFevhBttUcH7NuiqUViFmhbs7e0~LkyXzmQUbEkpnoSEcmiKepwDdpXj5GX~~uMlGGQjv4bSW~xdQ-qDa0iSUtm92SiKM-G40LEorMMFwi~TAmcsYKsXQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA

**Comment by chandler-stimson** [comment]
Use the latest version on Chrome (0.2.8). Open the interface and add this link using "Ctrl + V" (first you need to copy the link to the clipboard)

![a](https://user-images.githubusercontent.com/64349009/154003832-0a6b40b0-2304-43ca-8c6a-77e6134fc2ef.png)
