### ISSUE TITLE
Audio and Video in separate streams

### ISSUE THREAD

**Issue by arne182** [chandler-stimson/live-stream-downloader#17]
Hi,

Some websites like Brightcove separate the audio and video track. Is there an easy way to combine them again?

**Comment by chandler-stimson** [comment]
With [FFmpeg](https://www.ffmpeg.org/) it is simple
```
ffmpeg -i video.mp4 -i audio.wav -c:v copy -c:a aac output.mp4
```

Alternatively use https://chrome.google.com/webstore/detail/media-converter-and-muxer/ocnfecjfebnllnapjjoncgjnnkfmobjc
