### ISSUE TITLE
Feature Request - Auto naming or suggestion when saving

### ISSUE THREAD

**Issue by hyunki** [chandler-stimson/live-stream-downloader#18]
Hi thank you for the good app.
I hope there is auto naming feature which following the current tab name.

plus, sometimes, it fails to download and I can't remember which site was.
Please add site url below the status bar like this:

Number of Threads: 5
Referrer: https://turboviplay.com/
Download link: https://examplesite.com/view/7777
Tab name: The Cruel Intentions- Jawbreaker official Movie

**Comment by chandler-stimson** [comment]
You can alter filename pattern from the next release with `Ctrl + N` or `Command + N`.
