### ISSUE TITLE
Youtube and blacklist

### ISSUE THREAD

**Issue by trimechee** [chandler-stimson/live-stream-downloader#23]
Hello, thank you very much fot this amazing extension !

i have a look in the code and it seems youtube is blacklisted, it will be great to make extension outside the chrome store in order to download youtube streams and audio streams of youtube , ou update the firefox extension, or make another secret version without any blacklist and without censorship and we can downlaod just the  extension crx outside the chrome store in alternative browsers like Thorium browser, thank you very much :)

**Comment by trimechee** [comment]
My request is ignored ? not even a word ti tell me that you can't fix the problem ?  i can promote your extension in my twitter page

**Comment by chandler-stimson** [comment]
This extension is meant to download multi-segment media streams. It cannot download YouTube videos even if it is not on the exception list. This list only prevents soundtracks such as warning alerts from appearing in the badge area.

**Comment by trimechee** [comment]
Interesting ! Thank you :)

**Comment by helloyanis** [comment]
I'm reviving this, sorry, but I made an [fork](https://github.com/helloyanis/live-stream-downloader-unleashed) of this without the blocklist (and some code cleanup as well). You can check it out if you want @trimechee ! (It should be approved and installable through the firefox add-ons store soon)

**Comment by trimechee** [comment]
Ohh thank you very much to inform us Mr @helloyanis ! It looks very promising and exciting !  💯

 Just a question please, does Mr Chandler agree that other developers are inspired by his code?

Ahh indeed the link for the firefox store does not work yet.... we thank you so much again Mr @helloyanis and we suggest please to make an independent version of the extension in crx and xpi format so we no longer depend on store censorship, thanks a lot !

**Comment by helloyanis** [comment]
> Ohh thank you very much to inform us Mr @helloyanis ! It looks very promising and exciting ! 💯

Thank you! I'm happy you like it!

> Just a question please, does Mr Chandler agree that other developers are inspired by his code?

The code of the original add-on is under the Mozilla Public License 2.0, and [it's okay to take and edit it, as long as you provide source code](https://www.mozilla.org/en-US/MPL/2.0/FAQ/) (see Q9 and Q10)

> Ahh indeed the link for the firefox store does not work yet...

It should be up now, check it out!

> we thank you so much again Mr @helloyanis and we suggest please to make an independent version of the extension in crx and xpi format so we no longer depend on store censorship, thanks a lot !

I'm only using Firefox, so I don't know about crx files, but for the xpi file, you can just compress as zip all [thes files in the V3 folder](https://github.com/helloyanis/live-stream-downloader-unleashed/tree/master/v3) and rename the .zip to .xpi!

**Comment by trimechee** [comment]
Ohh great ! Thank you so much Mr Helloyanis for all these interesting and instructive informations and great kindness to inform us about the new amazinf fork and thank you all your efforts to make this new unleashed extension and also thanks fo  your other very useful extensions ! 💯 🥇

**Comment by trimechee** [comment]
Mr @helloyanis, sorry if we abuse from your great generosity and kindness, yes our beloved Live-stream-downloader-unleashed is the best open source extension to download videos! 🥇Thank you for the fork!

And also there is the famous FDM manager to donwnload from many websites:

https://www.freedownloadmanager.org/en/

(We have to right click/video after installing the fdm browser extension and the download manager, it seems sometimes there is an error message in chromium based browsers, so just click on the "ok button" and the error message disappears)

So It seems that google forced the FDM team to remove support of youtube in FDM , so FDM does not allow downloading from youtube, the solution is to use this awesome extension that can be added to FDM and which includes yt-dlp as well as FDM manager becomes more powerful and become able to download from youtube !

https://github.com/meowcateatrat/elephant

https://free-addons.org/

https://www.freedownloadmanager.org/board/viewtopic.php?f=1&t=18690



But the only problem is that this great extension even if it is updated regularly, it does not always include the latest version of yt-dlp which solves a lot of bugs, so my suggestion please if it doesn't bother you and I know it's very complicated to make extensions ! my request please is to analyze the code of this extension and if possible, make a fork which includes the latest version of yt-dlp because this extension uses a yt-dlp which dates from the month of March and is late by 3 versions:


3 youtube-dl updates have been released since the latest Elephant update which is based on yt-dlp 2024.03.10.

yt-dlp 2024.04.09
yt-dlp 2024.05.26
yt-dlp 2024.05.27


Thank you so much !

**Comment by helloyanis** [comment]
@trimechee ,
Sadly that one add-on is not open-source. Even if I can get the file and build a fork from it, it also requires installing an app on your PC which is also not open source, so that would take too much time and energy to find something that can work as a fork of this, plus the installable program is not under the MPL license, it would maybe not be legal to decompile it.

Plus, chrome is enforing Manifest v3 for all extensions ([see why it's bad](https://www.eff.org/deeplinks/2021/12/chrome-users-beware-manifest-v3-deceitful-and-threatening)) and I'm not wanting to support that which is why my fork is firefox only.

If you want to download youtube videos, there's [the Seal app](https://github.com/JunkFood02/Seal) that can do that quite well, by also using yt-dlp. Or you can just run [yt-dlp](https://github.com/yt-dlp/yt-dlp) itself on your PC.

**Comment by trimechee** [comment]
Ohh very very informative and important Mr @helloyanis ! ahh in fact I didn't really want you to do a fork but above all that you check the open source code of this extension because it seemed a little strange to me the confidentiality policy concerning an extension supposed to be open source and there,  you inform  me that this extension is not open source!!

 I don't accuse this extension of being suspicious but I find it surprising that an extension present on github is not open source....

so I think I will give up using this extension, while waiting for more information and investigation or for the code to become open source.....

Ohh sorry Mr Helloyanix, I live in a country which prohibits the transfer of money, but I will try to speak to friends who live abroad to tell them to use your magnificent extensions and maybe they will make donations to Mr Chandler and you :)


I have another question please Mr @helloyanis , the problem I encounter with Live-stream-downloader is when my internet connection becomes weak and to avoid jerky lag on streaming sites which have high quality video, I use Live-stream-downloader but I can't preview the video, i.e. I can't watch the video while downloading, a lot of downoad managers also don't allow me to watch the video while downloading which can be so long and it's tiring to wait for the download to finish, and so I spoke to the developer of File Centipede download manager  who confirmed this problem  
and he promised me to implement sequential downloading in the next version...and so I even spoke to Mr Chandler about implementing sequential download:

https://github.com/chandler-stimson/live-stream-downloader/issues/54


here the response of the developer of Fire Centipede : " For streaming media, the use of a single thread or multiple threads
for downloading makes no difference. During the download process, the
downloader creates independent files for each segment locally, which
are then merged into a single file after downloading. This is why the
file cannot be played. To resolve this, the solution is to add an
option to enable sequential downloading using only one connection and
creating a single file, allowing the player to function properly.
However, the player's fast-forward and rewind functions may not be
available. While many players support direct playback of m3u8 files,
they may not bypass certain download restrictions or decrypt content
like download manager do, unless making a new video player.....""

https://github.com/filecxx/FileCentipede/issues/755



for the moment, especially that my sister uses HDMI and my internet connection becomes weak and streaming video lags jerky, I fix this problem using FDM (number of threads 1) and i use also Coc Coc browser which allow sequential downloading so I can watch the video while it is downloading, and so my question Mr @helloyanis , do you think it is possible to implement sequential downloading in Live-stream-downloader or in your excellent fork File Downloader Unleashed or is it technically impossible ? the download is slow that's why the sequential download option is vital for me, thank you very much :)

Sorry also for this question, I saw that you wrote in french on one of your projects, so you are from France? because I know how to speak in French lol....

**Comment by helloyanis** [comment]
> I find it surprising that an extension present on github is not open source....

It seems like the add-on is open-source, but not the program you need to install to use it.

> I can't watch the video while downloading, a lot of downoad managers also don't allow me to watch the video while downloading

Try to play the M3U8 file through VLC! I'm not going to code an entire video player into the add-on (but it's open-source so feel free to do so if you want)

> you are from France?

Yeah, but these are the issue page of another english-speaking person so I'm speaking english for better comprehension by everyone

On the same subject I think it's better if we move from here to the fork's issue page to avoid overflowing this issue page, if you want to ask anything else

**Comment by helloyanis** [comment]
> I find it surprising that an extension present on github is not open source....

It seems like the add-on is open-source, but not the program you need to install to use it.

> I can't watch the video while downloading, a lot of downoad managers also don't allow me to watch the video while downloading

Try to play the M3U8 file through VLC! I'm not going to code an entire video player into the add-on (but it's open-source so feel free to do so if you want)

> you are from France?

Yeah, but these are the issue page of another english-speaking person so I'm speaking english for better comprehension by everyone

On the same subject I think it's better if we move from here to the fork's issue page to avoid overflowing this issue page, if you want to ask anything else.

**Comment by trimechee** [comment]
Ok, thank you ! of course  i didn't ask fr coding video player lol, juste if you can implement sequential donwload and so, we can play with potplayer, vlc.... the temporary file while is still downloaded, we are talking about an option that I asked Mr Chandler so o think it is not off topic :)  can you please tell us where your fork stores the temporary files i.e. in which Firefox folder it temporarily stores the parts of the file being downloaded ? I activated the Windiws 10 option which allows us to show hidden files and maybe we could playback temporary files donwloaded by yout fork before the download is finished, thank you !
