### ISSUE TITLE
Support Auto Close when [Media is Ready]

### ISSUE THREAD

**Issue by 3xploitzer0** [chandler-stimson/live-stream-downloader#27]
Please give us option to auto close window when **media is ready or download is complete**

**Comment by 3xploitzer0** [comment]
auto close didn't work

![image](https://user-images.githubusercontent.com/56762704/205024960-be3468e3-7541-4033-a06b-bcf366a31416.png)

**Comment by chandler-stimson** [comment]
You don't have it yet! A new option will be added to the options view as of the next release.
