### ISSUE TITLE
Result path

### ISSUE THREAD

**Issue by AskarTuganbaev** [chandler-stimson/live-stream-downloader#3]
Where can I find the saved video file?

**Comment by tipshot** [comment]
我也想知道，在哪里可以找到下载的文件。非常感谢！

**Comment by chandler-stimson** [comment]
If everything goes fine (no "E" appears as the badge text when the download reaches 100%), the extension should save to the default download directory. On Firefox, you may get the save dialog to select the destination folder.

**Comment by stephenjtong** [comment]
> If everything goes fine (no "E" appears as the badge text when the download reaches 100%), the extension should save to the default download directory. On Firefox, you may get the save dialog to select the destination folder.

I'm afraid no.

**Comment by chandler-stimson** [comment]
The latest release on Chrome (0.2.8) requests file location on each download, and it writes directly to the disk. So this issue should have been fixed. If not, reopen.
