### ISSUE TITLE
[Feature request] Grab file name from the page title

### ISSUE THREAD

**Issue by snwefly** [chandler-stimson/live-stream-downloader#31]
Option to Grab file name from the page title instead of server file name.

Thanks

**Comment by LiveNetworxHost** [comment]
ad.method()feature:shows.request
#27

**Comment by cocoloco111** [comment]
شكرا

**Comment by kubalav** [comment]
For me, the better choice of file name is from "og:title". It would be possible to add such an option?
@chandler-stimson

**Comment by chandler-stimson** [comment]
From the next release, you can extract content from the page and use that content as a filename mask with the following keyword:

```
[q:query|method|default-value]
```

For your case, you can use:

```
[q:meta[property="og:title"]|content|no title]
```

which is equivalent to:

```js
document.querySelector(meta[property="og:title"]).getAttribute('content')
```
