### ISSUE TITLE
Request to add the site to the BLOCKED_LIST

### ISSUE THREAD

**Issue by Artugr18** [chandler-stimson/live-stream-downloader#44]
I have a request to block movie downloads and add vip.darkfilms.top or/and darkfilms.top to the BLOCKED_LIST

**Comment by chandler-stimson** [comment]
Since the website requires login, I cannot verify the rule
https://github.com/chandler-stimson/live-stream-downloader/commit/ce98b5e9eeeacf201eb361ca43f9eec098e43abc#diff-af8d26bfcddcc46b8b5fc37b7d78512622a086a9aa4cf5d277f0d97c53f04c8eR7

**Comment by Artugr18** [comment]
Ok but will it work already or should I give you something else? And when is the next update on the Chrome Web Store with this fix?

**Comment by chandler-stimson** [comment]
> Ok but will it work already or should I give you something else? 

I have no idea. I cannot verify the rule. You can give the latest commit a try on the developer mode to evaluate the new rule

> And when is the next update on the Chrome Web Store with this fix?

Hopefully in a week. From the next release, the blocked list is dynamic and hence there is no need to update the extension to use the updates.

**Comment by Artugr18** [comment]
I have added the latest version of the add-on on firefox and from what I have checked it is no longer possible to download videos so it works as expected.

**Comment by Artugr18** [comment]
sorry to write again but i have another request could you please add another domain? I would like you to add vip.darkfilms.cc and have this one and the previous one stay permanently. Simply put, these are my 2 domains and I would like them to be secure. You can add it the same as the previous one because everything works on the old one.
