### ISSUE TITLE
Connection to the server is broken (BROKEN_PIPE -> Failed to execute 'put' on 'Cache': Partial response (status code 206) is unsupported)!  Use the box below to update the URL

### ISSUE THREAD

**Issue by schweet787** [chandler-stimson/live-stream-downloader#55]
Receive this error everytime I go to download; what am I doing wrong!?

Connection to the server is broken (BROKEN_PIPE -> Failed to execute 'put' on 'Cache': Partial response (status code 206) is unsupported)!

Use the box below to update the URL

**Comment by chandler-stimson** [comment]
What is the browser? Can you provide a sample page that has this issue?
