### ISSUE TITLE
Feature: allow plugin to be disabled for specific websites

### ISSUE THREAD

**Issue by soju-hananim** [chandler-stimson/live-stream-downloader#62]
I have found two websites that breaks as a result of having this plugin enabled. The breakage is rather significant since when this extension is enabled I can not login into those sites.

It would be beneficial to allow website to be whitelisted so that LSD doesn't inject its scripts onto those sites. For example, how uBlock Origin can be disabled for individual sites.

![Screenshot 2024-05-13 at 22 08 30](https://github.com/chandler-stimson/live-stream-downloader/assets/7364184/39c4663c-3baf-4bfd-a6b2-538a5dd0a8f5)

This would help to at least help return functionality for #49 too.

**Comment by chandler-stimson** [comment]
This extension does not inject anything into web pages unless you have the "Improve Media Detection" option checked. So, by the default configs,  there must be no issue.

If the issue occurs after having this option enabled, you need to provide more debugging info.

**Comment by soju-hananim** [comment]
humm... I did have that checked. I'll turn that off and run for a bit to see if the issue resolves.
