### ISSUE TITLE
Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by thatguyinfl** [chandler-stimson/live-stream-downloader#64]
Just started happenning on multiple computers in our house with multiple browsers:  Cannot read properties of undefined (reading 'length') when attempting to save. Sometime I can find a link that works from within the pluggin but it is not 1080p. I noticed the difference is in the URL length.  Short URLS work, Long ones do not.

**Comment by chandler-stimson** [comment]
I need an example page to regenerate the issue.

**Comment by thatguyinfl** [comment]
Thank you for the response.  I used your downloader on BODi (Beachbody)
forever with no issues.  It works on a system at my job which I am going to
verify the links today.

*Non-Working*
https://d197pzlrcwv1zr.cloudfront.net/bodi_LflyWRjdRAw_03072024/bodi_LflyWRjdRAw_03072024_Main.m3u8?Expires=1716635350&Key-Pair-Id=KLCJC6JAKT7X3&Signature=kDqPDqGpmr8HyAf~3K1x9yc~kBCydiD4LRStaSpPUZeAfDCAkUwqhYoyDfiFSGwN1-wRI8xGwrvV-h2gsYiD-fUDKsZjX~c9WfP80GsOsTnX3hsEx8F2kLgREFSu2MCsR3s7rrRHSsFzU4hluzIsCw49jn~PthyMhTl05MUqVNzlVGKPQbrljBuzDZzVnL4K8ysbIUXhHoFouERVhp7-ctfKJOioh4jVRL3Dw9LYjvM17ZtE3M4E9CpuM6MxGS3c~CMPnLlbVQzFQ6XX7hnqNY6HkZLo5ig7OOR8rRYEUqCX5KozXPSbM~KdRMW3OTGEcLQ~g7zTqsiEPab8lKX-qA__


*Working*
https://d197pzlrcwv1zr.cloudfront.net/bodi_LflyWRjdRAw_03072024/bodi_LflyWRjdRAw_03072024_Main_A.m3u8

Difference is the video, all the long links with "Main.m3u8" used to work.
The "Main_A.m3u8" is what works but it's not the correct video.  I will
verify at work today which links work.  Initially I thought it was a
specific system, then  specific browser but nothing works at my house.  I
will look more into it.

Thank you for the quick reply.

v/r

Luis B.

**Comment by thatguyinfl** [comment]
Just a heads up, works fine on Chrome, but no longer in Edge which is ok.
I appreciate the quick response.  Have a great day.
