### ISSUE TITLE
[Feature request] Send cookies with download request

### ISSUE THREAD

**Issue by SporgWaffle** [chandler-stimson/live-stream-downloader#68]
The extension is able to detect the .m3u8 link, but fails to download it because the website I'm using requires account login to watch the stream. I'm able to open the link in a new tab, but that only downloads the first .m3u8 file. Sending cookies with the download request would allow for programmatic downloading of the stream.

**Comment by chandler-stimson** [comment]
This extension sends cookies (haven't tried on private mode though). So there must be something else.

https://github.com/chandler-stimson/live-stream-downloader/blob/master/v3/data/job/mget/mget.js#L231

**Comment by SporgWaffle** [comment]
Thank you for the prompt response. I hadn't considered the fact that I was using Private browsing mode. I am able to download just fine in normal mode.
