### ISSUE TITLE
INVALID_SIZE error when download vtt file

### ISSUE THREAD

**Issue by chkchun** [chandler-stimson/live-stream-downloader#69]
Before recent update it able to download vtt file. Now when click to download vtt file, it failed due to "INVALID_SIZE".
I have tried with Edge, Chrome and Firefox. All failed due to "INVALID_SIZE".

**Comment by chandler-stimson** [comment]
Can you provide an example?

**Comment by chkchun** [comment]
![2024-06-29 10_50_57](https://github.com/chandler-stimson/live-stream-downloader/assets/24244855/30d2b9b7-2392-4a60-b8c7-b7226154112c)

**Comment by chkchun** [comment]
![2024-06-29 10_50_57](https://github.com/chandler-stimson/live-stream-downloader/assets/24244855/ec7c07db-e389-4562-939f-94216e0b5b9f)

**Comment by chandler-stimson** [comment]
It works for me on this website for instance. I need a sample page with the issue

https://www.nlm.nih.gov/scripts/videojs/examples/thumbsvtt.html

**Comment by chkchun** [comment]
The video is HLS encrypted and requires login credentials to be played. **However, when I reverted to the older version 0.4.4 (at Firefox), it started working fine! The vtt can be downloaded along with all its content.** 
The download for vtt has been malfunctioning from version 0.4.6.2 up to the latest version 0.4.7.1. I will continue using version 0.4.4 for the time being, as it is the version that works.

![2024-06-29 22_23_05](https://github.com/chandler-stimson/live-stream-downloader/assets/24244855/d80f9309-2661-402e-82fe-13b787878f1e)

![2024-06-29 22_24_36](https://github.com/chandler-stimson/live-stream-downloader/assets/24244855/7fc3f6f7-0646-4338-95d4-2f2ee55d767d)

**Comment by chandler-stimson** [comment]
Should be fixed by `0.4.7.3` release

**Comment by chkchun** [comment]
Thank you.
