### ISSUE TITLE
segment limit?

### ISSUE THREAD

**Issue by jonas1015119** [chandler-stimson/live-stream-downloader#7]
Im not sure if its a size or segment limit issue, but this Twitch VOD crashed on me twice close to completion after hours of downloading
http://dqrpb9wgowsf5.cloudfront.net/5538a59cdffa139d0fb6_hasanabi_40268411118_1603995612/chunked/index-dvr.m3u8

**Comment by chandler-stimson** [comment]
Try the latest version (0.2.8), it writes directly to the disk, so there is no memory shortage and hopefully no more crashes.
