### ISSUE TITLE
New open source extension with native integration with cli tools donwloader engines to detect more embed videos and supprt new platforms  and support and collect m3u8, mpd, ts files.....and display of the temporary download folder

### ISSUE THREAD

**Issue by trimechee** [chandler-stimson/live-stream-downloader#70]
Hello, i repost my message sent by email for reference reasons and to make an edit because I receive an error message from Live-stream-downloader that the file directory cache has been changed ...... when i preview the video in progress while be downloaded with vlc player or potplayer ! 

Hello again, thank you so much Mr Chandler @chandler-stimson  for the awesome great Live-stream-downloader extension ! 
Please i have suggestion, I found yesterday a new powerful open source extension which has a support for cli downloaders engines to download and gather the fragments of m3u8, mpd, ts.... files so maybe it can give ideas to our beloved Live-stream -downloader to integrate even more new downloaders tools and support even more streams protocols and streaming videos websites, thank you so much !
https://github.com/xifangczy/cat-catch/blob/master/README_en.md

Also, I noticed a strange thing, in the chromium 122 browsers, like supermium browser, thorium legacy browser, because currently I am using Windows 7 32 bit OS on my acine laptop, my laptop broke down, and so with these web browsers with Live-stream-downloader, I could see the video being downloaded in the download folder and I can preview the video before the download finishes because my internet connection can become very weak and I can wait plenty of time for the download to finish, hence the importance of previewing the video being downloaded, but on the catsxp 32 bit web browser for windows 7 os which is based on chromium or brave 126, I can no longer see the video being downloaded in the download folder and impossible to preview the video, for example in the third media player on this streaming site:

https://french-anime.com/exclue/1457-demon-slayedr.html

https://github.com/win32ss/supermium

https://github.com/Alex313031/thorium-legacy

https://www.catsxp.com/

and also vivaldi for windows 7  :

https://vivaldi.com/fr/download/

so we are hoping for an option to see the hidden temporary folder where the files are being downloaded in order to preview the video with potplayer, or vlc player, thank you very much!

**Comment by chandler-stimson** [comment]
Chrome creates temporary ".crswap" files during downloads. These can be played in external media players while the download is in progress.
I visited the website and observed that it recognizes the media link and produces this temporary file as part of the download process. So I am not sure what the problem is.

**Comment by chandler-stimson** [comment]
Most likely the external players are opening the file in read-only mode. Unfortunately there is nothing I can do to fix this. It is related to the external player and the OS.
