### ISSUE TITLE
My revolutionary discovery for watching streaming videos without having to wait for the the end of download  by using our favorite media players and suggestion to add a feature to send and open the m3u8 link with vlc or potplayer

### ISSUE THREAD

**Issue by trimechee** [chandler-stimson/live-stream-downloader#71]
I'm crying with joy, I'm relieved, I finally find how we can playback a video without having to wait for the download to finish, i make new issue to share my revolutionary sensational discovery that changes the game in the world and i make a suggestion for improvement to Mr Chnadler to better integrate this exceptional titanic news with Live donwload manager;

My discovery is while leaving the Live stream download stream display window open, copy the m3u8 link and put it in potplayer, then we can close the Live stream downloader window;

and I have a suggestion to better integrate and speed up the process, add a button in Live stream download "send the stream to potplayer or vlc open the m3u8 link in vlc or potplayer", maybe these open source extensions can help integrate this rare, revolutionary feature to speed up the process without the need to copy and paste the link into media players for smooth playback of the streaming video without the need of heavy web browser and playback lags even with weak internet  !

https://github.com/andy-portmen/external-application-button

https://github.com/andy-portmen/open-in-vlc

https://github.com/andy-portmen/open-in

https://github.com/andy-portmen/native-client

My discovery is useful for people who have a weak or old laptop I am currently using a 2012 Windows 7 laoptop and the video playback stutters lag seen I have an old OS, old cdec, old processor.....also it can be useful to those who have weak internet because you can change the parameters of the buffer network cache in VLC, Potplayer, Smplayer..... in addition discovery allows you to save bandwidth and ecology, often in animated films, movies ....there are boring passages and we can skip them with my discovery, thank you again Mr @chandler-stimson for this extension 🥇 💯 

EDIT UPDATE :   

Hello, may be it can help to implement preview feature, just to say i tried the "preview video" feature of "cat-catch" resource sniffing extension, it works but cat-catcher also offers an option to choose a local media player like vlc or potplayer to preview the video and I tried but it doesn't work....I even used external application button with cat catcher but I can't automatically preview the video with vlc or potplayer.... .but when I copy the url from Live stream download, it works 🥇 

https://github.com/xifangczy/cat-catch

**Comment by chandler-stimson** [comment]
There is no plan for live preview at this point. It is a complex task.

You can try https://webextension.org/listing/open-in-vlc.html if you would like to detect and send media to an external player.

**Comment by chandler-stimson** [comment]
> since Live stream downloader already offers us the possibility of copying the link of the url address to put it in vlc or potplayer or kikoplay or moon player or implay

For this purpose, the "Open in VLC" extensiom might be more suitable. It not only handles the task but also has the added benefit of launching the VLC application automatically.

> works once or twice then no longer works

Use command-line to send "http-referrer" as well as the link
