### ISSUE TITLE
Support of jwplayer : Important vital please add support of this capital website : fullmatchsports highlights

### ISSUE THREAD

**Issue by trimechee** [chandler-stimson/live-stream-downloader#75]
Hello, my laoptop broke down so I use my little laoptop which dates from 2012 windws 7 and when I watch a live football match, it's almost impossible to watch so much that it lags, the solution to this problem is to download the match highlights and the site "fullmatchsports.cc" seems to be one of the rare sites to offer long highlights, i.e. highlights which last 25 minutes or 30 minutes :  

https://fullmatchsports.cc/spain-vs-france-full-match-euro-2024/?tab=highlights

hence the capital importance of this website because many other highlights websites offer highlights of only 10 minutes.... and so the problem is it is impossible to download the video highlights on this rare site and we hope it will be fixed soon please, thank you very much :)

**Comment by chandler-stimson** [comment]
I added a new inspector to get the "jwplayer" playlist when the interface is open. Although you don't get the badge counter, the extension still tries to find the playlist when the interface is loaded. 

You can try the developer version to confirm.

**Comment by trimechee** [comment]
Although the great Mr @chandler-stimson  had the immense generosity and kindness to fix the problem with jwplayer and there is no more problem 💯 

   I share my new discovery, I find this tool, maybe it can help to detect and download jwplayer videos if the bug comes back :)

https://github.com/furkaninanc/jwplayer-scraper
