### ISSUE TITLE
Add a video quality indicator by adding feature "probe each stream found during the analysis (probe limit per stream (milliseconds) : 300

### ISSUE THREAD

**Issue by trimechee** [chandler-stimson/live-stream-downloader#78]
Hello, in the Live-stream-download settings, I chose the option "download the video with the lowest quality", however, for example on this site :

https://v5.voiranime.com/anime/kimetsu-no-yaiba-4-vf/kimetsu-no-yaiba-4-08-vf/

the extension always shows me 2 m3u8 streams, usually after experimenting I can figure out which of the 2 streams offered is the stream with the worst video quality and remember the name of the stream with the worst video quality.....but recently I downloaded a stream that has the highest quality even though in the settings, I chose the option "video with the worst quality", i have an old laptop, old hard drive, not very powerful connection, so it is important for me and probably for many other people not to make a mistake and to be able to easily download the video with the worst quality to preserve our bandwidth, time, hard drive durability, battery, energy.....

and so it will be great please to add a video quality indicator on the m3u8 streams,  maybe by adding an option like the one in the 3DYD youtube source plugin which has an option: "probe each stream found during the analysis (probe limit per stream (milliseconds) : 300 to detect the video quality and automatically display the desired video quality, thank you very much !

https://ys.3dyd.com/

**Comment by chandler-stimson** [comment]
If the player works properly, there will always be a "master.m3u8" manifest that includes all supported quality options. Simply use it, and the extension will display all available qualities for download.
