### ISSUE TITLE
=Failed: Failed to fetch

### ISSUE THREAD

**Issue by TzahiS** [chandler-stimson/live-stream-downloader#8]
Is it possible to download from sites that require login with username and password (I have them) before transferring to the movie website?
https://moneytalks.org.il/webinar/max_taxes_benefits/

https://fable.vzaar.com/v5/uspaes/112344/tHZjW2YA8EDc/22368796.ism/22368796-audio_eng=91376-video=541000.m3u8?ts=1607821445&amp;s=SaCD2vpkZLMO7GLtuJdqqSrM7%2BA=

**Comment by chandler-stimson** [comment]
Try with the latest release on Chrome (0.2.8). Reopen if it fails
