### ISSUE TITLE
Download freeze download stuck at 35%

### ISSUE THREAD

**Issue by trimechee** [chandler-stimson/live-stream-downloader#84]
Hello, again thank you so much for all your efforts to make this amazing extension !

So the video I'm trying to download is not heavy, just 50mb, usually the download is ultra fast,, bt this streaming platform seems to make modifications recently and we can't any more download videos because download freeze download stuck at 35% in our beloved Live stream donwloader , i even tried with other famous extension and i have an error message from other extension : hls encryption is not supported, and i tried with other extension, so i donwload video without audio !!

 we hope this will be fixed please because my favourite website puts many videos on this platform, thank you so much :)

The download bug is in second media player (LECTEUR MOON) in this site :

https://v5.voiranime.com/anime/mobile-suit-gundam-seed-vf/mobile-suit-gundam-seed-20-vf/

let's note my interesting awesome discover , i tired to preview with Open-in vlc extension but it doesn't work , so i go to vlc advanced settings and i go to gnu tls priority enryption and i choose performance priority to fast enryption and preview works with vlc !!

**Comment by chandler-stimson** [comment]
Thanks for the report. Please give the latest commit a try and let me know if it is fixed.

**Comment by trimechee** [comment]
Ohhh thank you for fixing this problem very quickly!!! 💯 🥇 

Truly Live Stream Downloader, objectively and honestly, is really indeed the best streaming video downloader in the whole world !!

because paid IDM encounters problems and the many recent change log 403 error download blocked forbidden testify to this, Cat catch is good but ffmpeg online sometimes encounters connection problems caused perhaps by cloudflare connections outside china according to the developer.....

and FDM is no longer able to download streaming videos from vidmoly and other platforms and the famous stream recorder extension doubled certification by google failed to download from this site by showing me the message impossible to decrypt hls.....
and the m3u8.dev/ extension which allowed to detect and download streaming streams was banned from the chrome store a few weeks ago probably dmca complaint....

https://chromewebstore.google.com/detail/m3u8-downloader-pro-hls-d/agiifopjckffghgiggmfnpbdamhpejfi

so our beloved Live stream downloader is the last of the mohicans and life saver!

I will try with the new version and make tests and I hope I will inform you about the results, thank you so much for your great efforts to fix all these problems :)

especially since this platform, even if it disappointed me because since the beginning of the summer, recent streaming videos only display 1080p quality which is a serious problem for my eee pc windows 7 32 bits, this platform still has several old videos of anime episodes before summer 2024 with 480p quality and precisely, I am currently downloading several old anime and the standard video quality allows me to download at lightning speed with our beloved Live Stream Downloader :)

I think the donations button or section should be more prominent maybe with the display of a pop-up window, and why not add an option "display some acceptable advertising during navigation" so that will support this magnificent project, thank you very much :)

**Comment by trimechee** [comment]
Oups, sorry,  i thought a new version was going to be put on chrome store or mozilla store, but it seems i have to use the new commits because the stable version is not yet available on the stores for days ?

i would like to test the beta version because it will help me to download quickly from this site and i have 30 episodes of the anime left to download, but i am not an expert and i have never tried that, so i have to click on Code/Download ZIP then unzip then enable the developer mode of the web browser then add the path of the unzipped folder ? i will try.....

**Comment by trimechee** [comment]
Well it seems I managed to install the new commits, I got 2 Live Stream Downloader extensions that have the same version number, I disabled the old extension to use the new extension, I have 3 streams, I choose the "master" stream and the download is super fast and no longer hangs at 35%, then once the download is finished, I playback with potplayer and there is only video without audio !

**Comment by chandler-stimson** [comment]
> I playback with potplayer and there is only video without audio !

The audio file is also offered when you select `master.m3u8`.

**Comment by trimechee** [comment]
Hi, that's strange, I don't remember seeing an audio file offered by master.m3u8 :  

Live Stream Downloader offered me 3 streams : master.m3u8, v1a1.m3u8.....


when i click on master .m3u8, the download starts instantly without showing me the audio file....or maybe i didn't pay attention....

well it doesn't matter, because for now i can preview vidmoly video with cat catch /potplayer with the use or urlprotocol : 

https://github.com/xifangczy/URLProtocol

and following the developer's advice by putting in the review settings:

potplayer://${url} /referer="${referer}"

and in addition, as a precaution, in the settings of 3DYD Youtube Source plugin that integrates with potplayer, I set the user agent identical to the user agent of my catsxp web browser that uses cat catch.....

and finally I can send the vidmoly streams to potplayer.....

but the problem is my sister uses HDMI a lot and often the playback in potplayer freezes that's why I have to download when my sister uses HDMI because the TV receiver doesn't work anymore and so my sister uses a lot of bandwidth to watch videos....

 and when there will be the stable version of our beloved Live Stream Downloader, i will try again because the commits i installed show me an error in the catsxp extensions page so the beta version seems not to have worked as it should....

so I chose the stream  master . m3u8 which had contrary to its usual a small size 25mb whereas usually, I download anime episodes with 50mb and my fear was confirmed, the master file downloaded weighs only 25mb and has no audio, same problem for Cat-catch, the master file in Cat-catch that I downloaded is a video without audio....it seems this platform separates the audio from the video and the solution seems to be to merge video with audio, maybe with third-party program like m3u8DL RE like Cat-catch does but the problem for me m3u8DL RE is not compatible with windows 7, or use ffmpeg online of Cat catch:

https://ffmpeg.bmmmd.com/

but despite that I followed the developer's recommandation to do ctrl+f5 to clear the cache of ffmpeg online, the last time I downloaded the final episode of an anime which weighs 500 MB and Cat-catch downloaded the small fragments then sent this small fragments to ffmpeg online but ffmpeg online did not open :(

maybe our belved Live stream downloader could advise us us an external tool of trust that we can install where after, we download the video only file and the audio only file, the external tool will merge the audio and video streams....

**Comment by chandler-stimson** [comment]
> when i click on master .m3u8, the download starts instantly without showing me the audio file....or maybe i didn't pay attention....

make sure the option to download highest quality is not on, so that the extension display the downloading options for "master.m3u8"

**Comment by trimechee** [comment]
Great ! Thank you so much for your precious advice :) 💯 🥇 

In fact from the beginning, I had set Live stream downloader to download the worst video quality, it worked without problem then once, Live stream downloader downloaded the highest video quality and there is a huge difference in size between 480p and 1080p, and I think I told you about it and you advised me to choose the master stream then I put the number corresponding to the desired quality ....

and so, for a few weeks, I have activated the setting to manually choose the stream to download to check and be sure,

but now, I will change the settings and do tests and inform you of the result, thank you again very much for this amazing jewel of technology essential for our lifes and our wallet because we no longer need to have a very high speed internet subscription to enjoy very high quality streaming video :)

**Comment by trimechee** [comment]
Hello Mr @chandler-stimson , there is good news and bad news, the good news is that I can copy the url address of the master m3u8 stream and paste the link in potplayer and I can playback the video with audio, but sometimes potplayer skips parts of the streaming video probably because my internet connection can become very weak because my sister uses HDMI at night, that's why I have to download,

so the bad news, I did new tests with the new stable version, I activated in the settings: choose the worst video quality, then I tried with manually choose the quality by putting a number, so yes with the setting manually choose the quality, there are 2 streams proposed when I click on master.m3u8, a video stream and an audio stream, the problem I don't need a video only file or an audio only file, I need a video with audio, I chose the video stream and I got a video without audio the same for the setting "choose the worst video quality", I get a video without audio, I specify I activated the setting "improved media detection",

so I changed the title of the issue because the download is no longer blocked but we get an audio only or video only file whereas previously, we got a video file with audio and video and audio was merged automatically, and we hope the issue will be re-opened again please, thank you very much!

**Comment by chandler-stimson** [comment]
This is not a bug. The website offers video-only and audio-only streams. You need to download both. Then use

```bash
ffmpeg -i video.mkv -i audio.mkv -c copy output.mkv
```

to get a normal stream.

Also you can start playing "video.mkv" in VLC and add audio track to it (for some streams it is not supported).

**Comment by trimechee** [comment]
Awesome ! Thank you so much for your essential and vital help :)

**Comment by trimechee** [comment]
So Mr @chandler-stimson , there is good news and good news :

good news is it is easy to download the separate audio and video streams but we no longer have to choose the master stream, we have to select the _index-v1 and _index-a1 streams which correspond to the video only and audi only streams.

The other good news is I went to dig into the potplayer settings because potplayer allows me to stretch the video and erase black bars on my small eee pc screen, and I discover in potplayer/open/load external audio that we can add audio to the video only and it works! I get in potplayer a video with audio that I can playback without problems !!!

So maybe to make it easier for beginners and non-experts, maybe add a red notice in the FAQ: some streaming streams have separate audio and video, we should download "_index-v1"  and "_index-a1" together and then play these separate streams with potplayer or vlc.....

and to make it even easier, maybe add an advanced option "download the audio and video streams at the same time if the extension detects separate audio and video streams", or add a warning pop-up window saying there are separate audio and video streams and the user must automatically download the separate audio and video streams.....

because we can get lost between the master stream, _index-v1 and _index-a1.....the master stream is a video without audio and we should avoid downloading it.....

maybe it would be better to rename the "index-v1 stream" to "video only v1" and the "index-a1 stream" to "audio only v1" to make it easier for beginners.....

Thanks again for this wonderful extension and your great help :)

**Comment by trimechee** [comment]
Hi Mr @chandler-stimson, sorry to bother you again but I think this news is important to show the importance of the microsoft edge store which allows to decrypt hls encrypted video contrary to chrome store policy and the importance of having a crx version outside the stores........

First let's clarify that i obviously like Live stream downloader which fixed quickly this bug and I do not criticize the extension Stream Recorder which compared to Live stream downloader, Stream Recorder and it is its right and it is legitimate to reward their efforts, Stream Recorder is not open source and displays a discreet ad not annoying on the download page and it is legitimate, so I speak of these informations just for information purposes to compare the policy of the edge store vs chrome store....


so i was desperate saddened destroyed that I could not download from this problematic site that i also contacted the developer of Stream Recorder :

https://www.hlsloader.com/

because Stream Recorder that I installed from chrome store could not also download from this complex site , and here is the response from the developer of Stream Recorder :

"Hi.
It seems like you have a few misunderstandings.
The Stream Recorder can internally merge audio and video even if they are stored separately in different TS files.
The site you mentioned (probably) has its TS files encrypted using HLS encryption.
And it's just that the Google Chrome version of the Stream Recorder cannot decrypt that "due to the Chrome Web Store's policies".
Again, just to be clear, it is not a technical issue, just that Google forbids distributing it in the blind.
Therefore, I am asking you to use the Edge version of the Stream Recorder.

The reason I cannot investigate the site is due to the laws of my country, not because of a network issue.
I can investigate content officially distributed by copyright holders, but I do not investigate content that is not.

Below is a zip file of the Stream Recorder for Edge.

https://www.altextension.com/stream/archives/edge_2_2_2.zip

Please refer to the following instructions for installation.

https://www.hlsloader.com/how_to_test/index.html

Thank you."

So i tried the experimental version for edge of Stream Recorder with Catsxp browser in my windows 7 os 32 bits and it works,  i have merged audio with video without external service ou local program.....

i can download from this problematic site and i got a merged video audio without the need of ffmpeg online so it is the proof that it is technically possible that a web extension can merge audio only and video only streams without the need of external service like ffmpeg online of Cat catch  !

https://ffmpeg.bmmmd.com/

and i have problems to merge audio and video streams with ffmpeg online and the developer of Cat Catch tells me my cpu is probably too old and don't support SMID instructions......

so i can't any more use ffmpeg online of Cat catch to merge audio and video streams and i  just talk about these informations just to inform that we can merge audio and video streams without the need of online tools or local tools like N_m3u8DL-RE which is compaible with Cat catch....


and I think it's important that our beloved Live-Stream-Downloader keeps a version for the microsoft edge store because the edge store policy allows to decrypt encrypted hls videos unlike the more restrictive chrome store, and also we hope please a crx version independent of the stores because I don't have edge browser and I can't install the Live Stream Downloader version from edge store because I use windows 7 os, I tried with Catsxp which in theory allows to install extensions from microsoft edge store but I couldn't install the extension in my windows 7 os.....

Thank you again very much for all your efforts to fix this problem and for this magnificent extension :)

**Comment by trimechee** [comment]
Hi again,, sorry there is a mystery that i can't clear up, the well known extension Stream Recorder from edge microsoft browser can merge audio only and video only streams from this problematic site without external service like ffmpeg online of Cat Catch, and our beoved Cat Catch is a wonderful complex extension and as excellent and powerful as Stream Recorder extension, why Stream Recorder can merge audio with video internally without the need of an external service ffmpeg online and Cat-Catch can't merge audio and video without the need of an external service like ffmpeg online ?!

It's really an enigma, because for me there is no doubt that the brilliant Mr @chandler-stimson  is as smart as the developer of Stream Recorder extension :)

**Comment by chandler-stimson** [comment]
There are two approaches: You can either record what's playing on the screen or locate the source (the M3U8 manifest) and download the segments. Recording captures both video and audio as it plays, without needing to handle decryption.

**Comment by trimechee** [comment]
Interesting and instructive ! Thank you :) 💯 

Precisely, what surprises me me is that I was able to download and merge audio and video from this problematic site without capture!

i see the "capture" button in the donwload page of Stream Recorder which advises to try the capture mode if the classic download does not work, and i spoke with the developer of Stream Recorder because Stream recorder extension downloaded from chrome store cannot download from this problematic site and shows me a message unsupported crypted hls.....

and the developer told me that he cannot analyze and test this site because the law of his country blocks this site but he advised me to try the edge version of Stream Recorder because the version of Stream Recorder from the chrome store is limited because google policy prohibits decrypting encrypted hls while it seems that edge store is more tolerant....

He explained to me that Stream Recorder can internally merge audio and video even if they are stored separately in different TS files and the site i mentioned (probably) has its TS files encrypted using HLS encryption and it's just that the Google Chrome version of the Stream Recorder cannot decrypt that "due to the Chrome Web Store's policies....

and he think  it is not a technical issue, just that Google forbids distributing it in the store and therefore, he asking me to use the edge version of the Stream Recorder, and the reason he cannot investigate the site is due to the laws of his country, not because of a network issue, and he can investigate content officially distributed by copyright holders, but I do not investigate content that is not....: 

https://www.altextension.com/stream/index.html 

https://microsoftedge.microsoft.com/addons/detail/altstream-recorder-hl/lmnlleihgiilhajakklebcmgacmmbngj


so , i see that therefore Stream Recorder merges audio and video autonomously internally without even the need for ffmpeg online, can our beloved Live stream donwloader take a look it on the data from the console (F12) of the developer mode to see how Stream Recorder manages and succeeds to merge audio and video please? 

because it's surprising to be able to do this without an external service and stream recorder itself says it doesn't use any external service and does all this internally!


the Stream Recorder download page  which appear when download page appear displays at the bottom several advanced parameters like check box concerning ffmpeg, is it ffmpeg webassembly? but the ffmpeg seems disabled in donwlad page, Stream Recorder seems to have found a trick to assemble and merge hls audio and video streams.....

For the moment, Live stream Downloader has done the hardest and most difficult, download crypted hls audio and video streams, merge audio and video is not so important since my discovery that we can assign a shortcut in potplayer to quickly add in 2 clicks an external audio track to the video only.....

but  I'm talking about merge audio and video especially for prestige and for beginners and non-experts, maybe it will be great that Live stream downloader mentions in the FAQ that potplayer can add external audio to video only file, or mentions and recall the important parameters to merge : "ffmpeg -i video.mkv -i audio.mkv -c copy output.mkv"....

I tried to add external audio via vlc player but it's long and tiring, potplayer is faster ....

Thanks!

Also, all this denotes the importance of the microsoft edge store which seems more flexible and less strict than the chrome store and we hope our beloved Live stream downloader will keep an uncensored version on the edge store please, and this denotes the importance of less strict alternative stores, for example the naver whale web browser store:

https://store.whale.naver.com/extensions/popular

or opera store....

and the importance of having a zip or crx version of Live stream downloader outside the stores far from censorship and aggressive control of the stores because if the video does not have a drm, no need for the overzealousness and unfair oppression of extensions....

i told the developer of Stream Recorder that i have windows 7 os and i can't install the edge store version of the extension from edge store and he was kind to send me a link to the zip edge version of the extension to install manually, and it worked, i was able to download and merge quickly  audio and video from this site without captue mode....

and we hope our beloved Live stream downloader will have an unofficial experimental beta version in zip or crx or xpi format intended for advanced users that we can easily install to test it if we encounter any problems, maybe the experimental version should be uploaded outside of github, maybe upload the beta version to dropbox or google drive or one drive or pcloud or other cloud platforms because I saw that Live stream downloader has put a small number of sites in a blacklist which suggests that there are spies who spy on Live stream downloader and want to illegally and abusively censor this magnificent extension which is legit and does not decrypt videos protected by drm ! 

Thank you very much :)

**Comment by trimechee** [comment]
Hello Mr @chandler-stimson , there is an increasingly worrying problem: yes I can play back video only and audio only stream with potplayer by activating the potlayer option "add external track", but sometimes on some streams downloaded by the extension, there is a chronology problem i.e. the audio is not perfectly synchronized with the video and there is a time lag, I don't know if the problem comes from potplayer or from the streams downloaded separately .....

I found these free online services:

ffmpeg online:

https://ffmpeg.bmmmd.com/

and section: " use Download M3U8 Video
TS Download (Recommend): Download the video in TS format."

of

https://m3u8.dev/

https://m3u8play.dev/

and online service :

https://blog.luckly-mjw.cn/tool-show/m3u8-downloader/index-en.html

https://blog.luckly-mjw.cn/tool-show/media-source-extract/example/index.html
https://github.com/Momo707577045/m3u8-downloader

and online service :

https://youwen21.github.io/

https://youwen21-github-io.pages.dev/

https://player.himyou.com/

https://github.com/youwen21/youwen21.github.io

for merge audio and video, these websites are free and I think even extensions can use them by automatically sending ffmpeg commands to merge audio and video streams in these sites, what do you think of my idea?

i don't think that the owners of https://m3u8.dev/ and https://ffmpeg.bmmmd.com/ or https://youwen21.github.io/ or https://blog.luckly-mjw.cn/tool-show/m3u8-downloader/index-en.html will refuse these operations of merging audio and video streams coming from Live stream downloader because that's the reason for their existence, to make life easier for users with these free online tools, plus it will bring them traffic and the attendance of their sites (and maybe advertising revenue if they decide to broadcast ads) would increase thanks to the users of Live stream downloader!

or can Live stream downloader automatically show us maybe in a pop-up window the audio and video merge commands in order to easily copy these commands into local programs, for example I use the excellent Media-downloader to download audio and video from sites supported by yt-dlp :

https://github.com/mhogomchungu/media-downloader

and Media-donwloader is a beautiful GUI of yt-dlp and has integration with ffmpeg, aria2c, wget....and may be able to merge audio and video streams from Live Stream Downloader, and I even asked the great developer of Media-downloader Mr @mhogomchungu to add native support for Live stream donwloader !
